title: Machine Learning & Data Science Enthusiast | Innovator in AI 
title_separator          : "-"
name                     :  Iresha
logo: /assets/images/Iresha.jpg
description: Iresha Sandamali
show_downloads: true
theme: jekyll-theme-minimal
url : https://ireshasd.github.io/Iresha-Sandamali/


# navbar_links:
#   - label: About
#     url: /pages/About.md
#   - label: Education
#     url: /pages/Education.md
#   - label: Projects
#     url: /pages/Projects.md
#   - label: Work Experience
#     url: /pages/Work-Experience.md

